stages:
- test
- package
- containerize

Test:
  stage: test
  tags:
  - docker
  script:
  - sbt clean update test

Package:
  stage: package
  dependencies:
  - Test
  tags:
  - docker
  script:
  - sbt universal:packageZipTarball
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_SHA}"
    paths:
    - target/universal/*
    when: on_success
  only:
  - master

Containerize:
  stage: containerize
  tags:
  - docker
  dependencies:
  - Package
  script:
  - docker build -t payvision/${CI_PROJECT_NAME}:latest -t payvision/${CI_PROJECT_NAME}:${CI_COMMIT_SHA} .
  only:
  - master
